version: '3.4'
services:
  sticker-kit:
    image: sticker-api:latest
    build: "./"
    working_dir: /app
    command: bash -c "uvicorn main:app --reload --host 0.0.0.0 --port 80"
    ports:
    - '8000:8000'
    networks:
    - all


networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"